
media: media
content:
  - name: posts
    label: Posts
    type: collection
    path: 'src/pages/posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: layout
        label: Layout
        type: string
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: layouts
    label: Layouts
    type: collection
    path: 'src/layouts'
    filename: '{primary}.astro'
  - name: index
    label: Index
    path: src/pages/index.astro
    type: file
  - name: yx-cloudflare
    label: YX Cloudflare
    path: yx.cloudflare.txt
    type: file
