apiVersion: apps/v1
kind: Deployment
metadata:
  name: att-n-deployment
  labels:
    app: {{ .Values.deployment.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.app }}
    spec:
      containers:
      - name: attc
        #image: i-t555-i555:0.0.0
        image: ghcr.io/ajprod5555/yxatt678:0.0.1
        ports:
        - containerPort: 8080
