
name: Main
run-name: ${{ github.actor }}!
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.YXATT678_GH_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/ajprod5555/yxatt678:latest --tag ghcr.io/ajprod5555/yxatt678:0.0.2
          docker push ghcr.io/ajprod5555/yxatt678:latest
          docker push ghcr.io/ajprod5555/yxatt678:0.0.2
