
name: Main
run-name: ${{ github.actor }}!
on: [push]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.YXATT678_GH_TOKEN}}

      - name: Package Helm chart
        run: |
          helm package .

      - name: Push Helm chart to GHCR
        run: |
          helm push att-0.0.1.tgz oci://ghcr.io/ajprod5555/yx439556
